import { Activity, RefreshCw, Search } from "lucide-react";
import Link from "next/link";
import { AppShell } from "../components/app-shell";
import { sampleVehicles } from "../lib/vehicle-data";

export default function Home(){return <AppShell>
  <header className="topbar"><div><p className="eyebrow">OPERATIONS</p><h1>Fleet & VIN Dashboard</h1></div><Link className="primary" href="/sync"><RefreshCw size={17}/> Sync DTNA</Link></header>
  <section className="lookup-card"><div><p className="eyebrow">QUICK LOOKUP</p><h2>Find any vehicle</h2><p>Search full VIN, serial number, customer, sales order, or model.</p></div><Link className="searchbox" href="/lookup"><Search size={20}/><span style={{flex:1,color:"#6b778c"}}>Enter VIN or serial number…</span><button>Look up</button></Link></section>
  <section className="stats"><article><span>Vehicles</span><strong>—</strong><small>Connect database to populate</small></article><article><span>DTNA Orders</span><strong>—</strong><small>Imported + synchronized</small></article><article><span>In-Service Dates</span><strong>—</strong><small>Dealer Reporting enrichment</small></article><article><span>Changes</span><strong>—</strong><small>Normalized real changes only</small></article></section>
  <section className="panel"><div className="panel-head"><div><p className="eyebrow">VEHICLES</p><h2>Current vehicle records</h2></div><div className="actions"><Link className="ghost" href="/import">Upload Excel / CSV</Link><Link className="ghost" href="/vehicles">View all</Link></div></div><div className="table-wrap"><table><thead><tr><th>VIN</th><th>Serial</th><th>Model</th><th>Customer</th><th>Status</th><th>Projected</th></tr></thead><tbody>{sampleVehicles.map(v=><tr key={v.vin}><td><Link className="mono" href={`/vehicles/${v.vin}`}>{v.vin}</Link></td><td>{v.serial}</td><td>{v.model}</td><td>{v.customer}</td><td><span className="status">{v.status}</span></td><td>{v.projectedDelivery||"—"}</td></tr>)}</tbody></table></div><p className="demo-note">Generalized demo records only. Production records load after Supabase import.</p></section>
  <section className="grid-two"><article className="panel compact"><p className="eyebrow">CHANGE HISTORY</p><h2>Meaningful events only</h2><p>The new comparison layer normalizes DTNA values before logging changes, eliminating the false “CURRENT: date → same date” events from the desktop workflow.</p><Link className="primary" href="/history"><Activity size={17}/> Open history</Link></article><article className="panel compact"><p className="eyebrow">SYSTEM</p><h2>Vercel + DTNA worker</h2><p>The website, database and user experience run in the cloud. The DTNA browser/MFA flow remains isolated in a secure Playwright worker.</p><div className="flow"><span>DTNA</span><b>→</b><span>Worker</span><b>→</b><span>API</span><b>→</b><span>Database</span></div></article></section>
</AppShell>}
